// ============================================================
// lib/practice/seed-questions.ts — Comprehensive DSC Question Bank
// ============================================================
// Multi-medium (English & Telugu), multi-subject, multi-class
// ============================================================

import type { PracticeQuestion } from '@/types/practice'

export const SEED_QUESTIONS: PracticeQuestion[] = [
  // ────────────────────────────────────────────────────────────
  // ENGLISH MEDIUM — ENGLISH SUBJECT
  // ────────────────────────────────────────────────────────────
  {
    id: 'eng-tns-01',
    question_id: 'ENG_TNS_001',
    medium: 'english',
    subject: 'English',
    class_level: 'Class 8',
    chapter: 'Grammar',
    topic: 'Tenses',
    subtopic: 'Present Perfect Continuous',
    difficulty: 'Medium',
    question_type: 'MCQ',
    question: 'Identify the sentence with the correct usage of the Present Perfect Continuous tense:',
    option_a: 'She has been working on this project since three hours.',
    option_b: 'She has been working on this project for three hours.',
    option_c: 'She is working on this project since three hours.',
    option_d: 'She had been worked on this project for three hours.',
    correct_answer: 'B',
    explanation: 'We use "for" with a duration/period of time ("three hours") and "since" with a specific point in time (e.g. "since 9 AM"). Option B is grammatically accurate.',
    source_type: 'SCERT 8th English',
    language: 'english',
    tags: 'tenses,present perfect continuous,grammar',
  },
  {
    id: 'eng-tns-02',
    question_id: 'ENG_TNS_002',
    medium: 'english',
    subject: 'English',
    class_level: 'Class 7',
    chapter: 'Grammar',
    topic: 'Tenses',
    subtopic: 'Past Perfect',
    difficulty: 'Hard',
    question_type: 'MCQ',
    question: 'She ______ her homework before the teacher arrived in the classroom.',
    option_a: 'completes',
    option_b: 'has completed',
    option_c: 'had completed',
    option_d: 'is completing',
    correct_answer: 'C',
    explanation: '"Had completed" is in the Past Perfect tense. When two actions happened in the past, the earlier completed action takes Past Perfect (had + V3), while the subsequent action takes Simple Past ("arrived").',
    source_type: 'AP DSC 2019 Paper',
    language: 'english',
    tags: 'tenses,past perfect,grammar',
  },
  {
    id: 'eng-tns-03',
    question_id: 'ENG_TNS_003',
    medium: 'english',
    subject: 'English',
    class_level: 'Class 6',
    chapter: 'Grammar',
    topic: 'Tenses',
    subtopic: 'Simple Present',
    difficulty: 'Easy',
    question_type: 'MCQ',
    question: 'The Earth ______ around the Sun.',
    option_a: 'revolve',
    option_b: 'revolves',
    option_c: 'is revolving',
    option_d: 'revolved',
    correct_answer: 'B',
    explanation: 'Universal scientific truths and general facts always take the Simple Present tense. Since "The Earth" is third-person singular, we add "-s" to form "revolves".',
    source_type: 'SCERT 6th English',
    language: 'english',
    tags: 'tenses,simple present,grammar',
  },
  {
    id: 'eng-prep-01',
    question_id: 'ENG_PREP_001',
    medium: 'english',
    subject: 'English',
    class_level: 'Class 7',
    chapter: 'Grammar',
    topic: 'Articles & Prepositions',
    subtopic: 'Prepositions of Place',
    difficulty: 'Easy',
    question_type: 'MCQ',
    question: 'The headmaster distributed the prizes _______ the outstanding students.',
    option_a: 'between',
    option_b: 'among',
    option_c: 'with',
    option_d: 'across',
    correct_answer: 'B',
    explanation: '"Among" is used for distribution or relationships involving more than two persons or objects. "Between" is generally used for exactly two.',
    source_type: 'SCERT 7th English',
    language: 'english',
    tags: 'prepositions,grammar',
  },
  {
    id: 'eng-prep-02',
    question_id: 'ENG_PREP_002',
    medium: 'english',
    subject: 'English',
    class_level: 'Class 8',
    chapter: 'Grammar',
    topic: 'Articles & Prepositions',
    subtopic: 'Definite Article',
    difficulty: 'Medium',
    question_type: 'MCQ',
    question: 'He is ______ European scholar visiting our university today.',
    option_a: 'a',
    option_b: 'an',
    option_c: 'the',
    option_d: 'no article',
    correct_answer: 'A',
    explanation: 'Although "European" begins with the vowel letter "E", it begins with the consonant sound /juː/ (like "you"). Hence, the indefinite article "a" is used.',
    source_type: 'AP DSC Model Paper',
    language: 'english',
    tags: 'articles,grammar',
  },
  {
    id: 'eng-pos-01',
    question_id: 'ENG_POS_001',
    medium: 'english',
    subject: 'English',
    class_level: 'Class 6',
    chapter: 'Grammar',
    topic: 'Parts of Speech',
    subtopic: 'Adverbs',
    difficulty: 'Easy',
    question_type: 'MCQ',
    question: 'Identify the adverb in the following sentence: "The elderly man walked very slowly across the street."',
    option_a: 'elderly',
    option_b: 'walked',
    option_c: 'slowly',
    option_d: 'street',
    correct_answer: 'C',
    explanation: '"Slowly" is an adverb of manner modifying the verb "walked". ("Elderly" is an adjective modifying "man").',
    source_type: 'SCERT 6th English',
    language: 'english',
    tags: 'parts of speech,adverb',
  },
  {
    id: 'eng-pos-02',
    question_id: 'ENG_POS_002',
    medium: 'english',
    subject: 'English',
    class_level: 'Class 9',
    chapter: 'Grammar',
    topic: 'Parts of Speech',
    subtopic: 'Conjunctions',
    difficulty: 'Medium',
    question_type: 'MCQ',
    question: 'Select the correlative conjunction pair in: "Neither the principal nor the teachers were present."',
    option_a: 'Neither ... nor',
    option_b: 'the ... were',
    option_c: 'nor ... present',
    option_d: 'principal ... teachers',
    correct_answer: 'A',
    explanation: '"Neither ... nor" is a correlative conjunction pair used to link two negative elements of equal grammatical rank.',
    source_type: 'SCERT 9th English',
    language: 'english',
    tags: 'parts of speech,conjunctions',
  },
  {
    id: 'eng-voi-01',
    question_id: 'ENG_VOI_001',
    medium: 'english',
    subject: 'English',
    class_level: 'Class 9',
    chapter: 'Grammar',
    topic: 'Types of Sentences',
    subtopic: 'Active & Passive Voice',
    difficulty: 'Hard',
    question_type: 'MCQ',
    question: 'Change the voice: "They are repairing the bridge."',
    option_a: 'The bridge is repaired by them.',
    option_b: 'The bridge has been repaired by them.',
    option_c: 'The bridge is being repaired by them.',
    option_d: 'The bridge was being repaired by them.',
    correct_answer: 'C',
    explanation: 'Present continuous active voice (is/am/are + V-ing) converts to passive voice as: Object + is/am/are + being + V3 + by + Subject.',
    source_type: 'AP DSC 2018 Paper',
    language: 'english',
    tags: 'passive voice,voice',
  },
  {
    id: 'eng-voc-01',
    question_id: 'ENG_VOC_001',
    medium: 'english',
    subject: 'English',
    class_level: 'Class 8',
    chapter: 'Vocabulary',
    topic: 'Pronunciation',
    subtopic: 'Synonyms & Antonyms',
    difficulty: 'Medium',
    question_type: 'MCQ',
    question: 'What is the closest synonym of the word "CANDID"?',
    option_a: 'Secretive',
    option_b: 'Frank and outspoken',
    option_c: 'Deceitful',
    option_d: 'Hesitant',
    correct_answer: 'B',
    explanation: '"Candid" means truthful, straightforward, and sincere; frank. Options A and C are antonyms.',
    source_type: 'SCERT 8th Vocabulary',
    language: 'english',
    tags: 'vocabulary,synonyms',
  },
  {
    id: 'eng-met-01',
    question_id: 'ENG_MET_001',
    medium: 'english',
    subject: 'English',
    class_level: 'SGT',
    chapter: 'Pedagogy',
    topic: 'English Methodology',
    subtopic: 'Language Skills (LSRW)',
    difficulty: 'Medium',
    question_type: 'MCQ',
    question: 'Which of the following language skills are considered "Productive" or "Expressive" skills?',
    option_a: 'Listening and Reading',
    option_b: 'Speaking and Writing',
    option_c: 'Listening and Speaking',
    option_d: 'Reading and Writing',
    correct_answer: 'B',
    explanation: 'Listening and Reading are Receptive (Passive) skills as information is received. Speaking and Writing are Productive (Active/Expressive) skills as language is generated.',
    source_type: 'D.Ed English Pedagogy',
    language: 'english',
    tags: 'pedagogy,lsrw,methodology',
  },

  // ────────────────────────────────────────────────────────────
  // TELUGU MEDIUM — TELUGU SUBJECT (తెలుగు భాష I)
  // ────────────────────────────────────────────────────────────
  {
    id: 'tel-san-01',
    question_id: 'TEL_SAN_001',
    medium: 'telugu',
    subject: 'Telugu',
    class_level: 'Class 8',
    chapter: 'వ్యాకరణం',
    topic: 'సంధులు & సమాసాలు',
    subtopic: 'సవర్ణదీర్ఘ సంధి',
    difficulty: 'Easy',
    question_type: 'MCQ',
    question: '"రామాలయం" అనే పదాన్ని విడదీసి సంధిని గుర్తించండి:',
    option_a: 'రామ + ఆలయం (సవర్ణదీర్ఘ సంధి)',
    option_b: 'రాము + ఆలయం (ఉత్వ సంధి)',
    option_c: 'రామ + అయం (గుణ సంధి)',
    option_d: 'రామాల + యం (యడాగమ సంధి)',
    correct_answer: 'A',
    explanation: 'అ, ఇ, ఉ, ఋ లకు అవే అచ్చులు పరమైనప్పుడు వాని దీర్ఘము ఏకాదేశమగును. రామ (అ) + ఆలయం (ఆ) = రామాలయం (సవర్ణదీర్ఘ సంధి).',
    source_type: 'AP SCERT 8వ తరగతి తెలుగు',
    language: 'telugu',
    tags: 'తెలుగు,సంధులు,వ్యాకరణం',
  },
  {
    id: 'tel-san-02',
    question_id: 'TEL_SAN_002',
    medium: 'telugu',
    subject: 'Telugu',
    class_level: 'Class 9',
    chapter: 'వ్యాకరణం',
    topic: 'సంధులు & సమాసాలు',
    subtopic: 'కర్మధారయ సమాసం',
    difficulty: 'Medium',
    question_type: 'MCQ',
    question: '"ముల్లోకాలు" అనునది ఏ సమాసము?',
    option_a: 'ద్వంద్వ సమాసము',
    option_b: 'ద్విగు సమాసము',
    option_c: 'బహువ్రీహి సమాసము',
    option_d: 'రూపక సమాసము',
    correct_answer: 'B',
    explanation: 'సంఖ్యా పూర్వః ద్విగుః - పూర్వపదం సంఖ్యావాచకంగా ఉంటే దానిని "ద్విగు సమాసము" అంటారు. మూడు సంఖ్య గల లోకాలు = ముల్లోకాలు.',
    source_type: 'AP SCERT 9వ తరగతి తెలుగు',
    language: 'telugu',
    tags: 'తెలుగు,సమాసాలు,ద్విగు',
  },
  {
    id: 'tel-cha-01',
    question_id: 'TEL_CHA_001',
    medium: 'telugu',
    subject: 'Telugu',
    class_level: 'Class 10',
    chapter: 'ఛందస్సు',
    topic: 'ఛందస్సు & అలంకారాలు',
    subtopic: 'వృత్త పద్యాలు',
    difficulty: 'Hard',
    question_type: 'MCQ',
    question: '"న-జ-భ-జ-జ-జ-ర" అనే గణాలు వచ్చే వృత్త పద్యం ఏది?',
    option_a: 'ఉత్పలమాల',
    option_b: 'చంపకమాల',
    option_c: 'శార్దూలము',
    option_d: 'మత్తేభము',
    correct_answer: 'B',
    explanation: 'చంపకమాల పద్యంలో ప్రతి పాదంలో "న, జ, భ, జ, జ, జ, ర" అనే 7 గణాలు (మొత్తం 21 అక్షరాలు) ఉంటాయి. యతిస్థానం 11వ అక్షరం.',
    source_type: 'AP DSC 2019 Telugu Paper',
    language: 'telugu',
    tags: 'ఛందస్సు,చంపకమాల,పద్యాలు',
  },
  {
    id: 'tel-sah-01',
    question_id: 'TEL_SAH_001',
    medium: 'telugu',
    subject: 'Telugu',
    class_level: 'Class 7',
    chapter: 'సాహిత్యం',
    topic: 'తెలుగు సాహిత్యం & కవులు',
    subtopic: 'కవిత్రయం',
    difficulty: 'Easy',
    question_type: 'MCQ',
    question: 'ఆంధ్ర మహాభారతాన్ని రచించిన "కవిత్రయం" లో మొదటి కవి ఎవరు?',
    option_a: 'తిక్కన',
    option_b: 'నన్నయ',
    option_c: 'ఎర్రన',
    option_d: 'పోతన',
    correct_answer: 'B',
    explanation: '11వ శతాబ్దానికి చెందిన ఆది కవి నన్నయ మహాభారతంలోని ఆది, సభ, అరణ్య పర్వంలో కొంత భాగాన్ని రచించారు.',
    source_type: 'AP SCERT తెలుగు వాచకం',
    language: 'telugu',
    tags: 'సాహిత్యం,కవిత్రయం,నన్నయ',
  },
  {
    id: 'tel-met-01',
    question_id: 'TEL_MET_001',
    medium: 'telugu',
    subject: 'Telugu',
    class_level: 'SGT',
    chapter: 'బోధనా పద్ధతులు',
    topic: 'భాషా బోధనా పద్ధతులు',
    subtopic: 'పఠన నైపుణ్యాలు',
    difficulty: 'Medium',
    question_type: 'MCQ',
    question: 'విద్యార్థులలో గ్రహణశక్తిని, వేగాన్ని పెంచడానికి ఉత్తమమైన పఠన పద్ధతి ఏది?',
    option_a: 'ప్రకాశ పఠనం (బాహ్య పఠనం)',
    option_b: 'మౌన పఠనం',
    option_c: 'ఆదర్శ పఠనం',
    option_d: 'అనుకరణ పఠనం',
    correct_answer: 'B',
    explanation: 'మౌన పఠనం ద్వారా విద్యార్థి అంతర్గతంగా ఆలోచిస్తూ భావాన్ని గ్రహించే శక్తిని, చదివే వేగాన్ని పెంచుకుంటాడు.',
    source_type: 'డి.ఎడ్ తెలుగు మెథడాలజీ',
    language: 'telugu',
    tags: 'బోధనా పద్ధతులు,మౌన పఠనం',
  },

  // ────────────────────────────────────────────────────────────
  // ENGLISH & TELUGU MEDIUM — MATHEMATICS (గణితం)
  // ────────────────────────────────────────────────────────────
  {
    id: 'math-num-01',
    question_id: 'MATH_NUM_001',
    medium: 'english',
    subject: 'Mathematics',
    class_level: 'Class 6',
    chapter: 'Arithmetic',
    topic: 'Number System',
    subtopic: 'LCM & HCF',
    difficulty: 'Easy',
    question_type: 'MCQ',
    question: 'The HCF of two prime numbers a and b is always:',
    option_a: 'a × b',
    option_b: '0',
    option_c: '1',
    option_d: 'a + b',
    correct_answer: 'C',
    explanation: 'By definition, prime numbers have only 1 and themselves as factors. Therefore, the Highest Common Factor (HCF) of any two distinct prime numbers is always 1.',
    source_type: 'SCERT 6th Maths',
    language: 'english',
    tags: 'maths,number system,hcf',
  },
  {
    id: 'math-num-01-tel',
    question_id: 'MATH_NUM_001_TEL',
    medium: 'telugu',
    subject: 'Mathematics',
    class_level: 'Class 6',
    chapter: 'అంకగణితం',
    topic: 'సంఖ్యామానం',
    subtopic: 'క.సా.గు & గ.సా.భా',
    difficulty: 'Easy',
    question_type: 'MCQ',
    question: 'ఏవైనా రెండు ప్రధాన సంఖ్యల గ.సా.భా (HCF) ఎల్లప్పుడూ ఎంత అవుతుంది?',
    option_a: '0',
    option_b: '1',
    option_c: 'వాటి లబ్ధం',
    option_d: 'వాటి మొత్తం',
    correct_answer: 'B',
    explanation: 'ప్రధాన సంఖ్యలకు 1 మరియు అదే సంఖ్య మాత్రమే కారణాంకాలుగా ఉంటాయి. కావున ఏ రెండు ప్రధాన సంఖ్యల ఉమ్మడి గరిష్ట కారణాంకం (గ.సా.భా) ఎల్లప్పుడూ 1 అవుతుంది.',
    source_type: 'AP SCERT 6వ గణితం',
    language: 'telugu',
    tags: 'గణితం,సంఖ్యామానం,గసాభా',
  },
  {
    id: 'math-geo-01',
    question_id: 'MATH_GEO_001',
    medium: 'english',
    subject: 'Mathematics',
    class_level: 'Class 8',
    chapter: 'Geometry',
    topic: 'Geometry & Mensuration',
    subtopic: 'Triangles',
    difficulty: 'Medium',
    question_type: 'MCQ',
    question: 'In a right-angled triangle, if the hypotenuse is 13 cm and one side is 5 cm, find the length of the other side:',
    option_a: '10 cm',
    option_b: '11 cm',
    option_c: '12 cm',
    option_d: '8 cm',
    correct_answer: 'C',
    explanation: 'By Pythagoras theorem: Hypotenuse² = Base² + Height² => 13² = 5² + x² => 169 - 25 = x² => x² = 144 => x = 12 cm.',
    source_type: 'SCERT 8th Maths',
    language: 'english',
    tags: 'maths,geometry,pythagoras',
  },

  // ────────────────────────────────────────────────────────────
  // SCIENCE (సాధారణ సైన్స్)
  // ────────────────────────────────────────────────────────────
  {
    id: 'sci-bio-01',
    question_id: 'SCI_BIO_001',
    medium: 'english',
    subject: 'Science',
    class_level: 'Class 7',
    chapter: 'Biology',
    topic: 'Living World',
    subtopic: 'Photosynthesis',
    difficulty: 'Easy',
    question_type: 'MCQ',
    question: 'Which pigment present in green plant cells is responsible for absorbing sunlight during photosynthesis?',
    option_a: 'Hemoglobin',
    option_b: 'Chlorophyll',
    option_c: 'Carotene',
    option_d: 'Melanin',
    correct_answer: 'B',
    explanation: 'Chlorophyll is the green pigment located in the chloroplasts of plant cells that traps solar energy required to synthesize glucose during photosynthesis.',
    source_type: 'SCERT 7th Science',
    language: 'english',
    tags: 'science,biology,chlorophyll',
  },
  {
    id: 'sci-bio-01-tel',
    question_id: 'SCI_BIO_001_TEL',
    medium: 'telugu',
    subject: 'Science',
    class_level: 'Class 7',
    chapter: 'జీవశాస్త్రం',
    topic: 'జీవ ప్రపంచం',
    subtopic: 'కిరణజన్య సంయోగక్రియ',
    difficulty: 'Easy',
    question_type: 'MCQ',
    question: 'మొక్కల ఆకులలో సౌరశక్తిని గ్రహించి కిరణజన్య సంయోగక్రియకు తోడ్పడే వర్ణద్రవ్యం ఏది?',
    option_a: 'హిమోగ్లోబిన్',
    option_b: 'పత్రహరితం (క్లోరోఫిల్)',
    option_c: 'కెరోటిన్',
    option_d: 'మెలనిన్',
    correct_answer: 'B',
    explanation: 'హరితరేణువుల్లో ఉండే పత్రహరితం సూర్యకాంతిని శోషించుకుని రసాయన శక్తిగా మార్చడంలో ముఖ్యపాత్ర పోషిస్తుంది.',
    source_type: 'AP SCERT 7వ సైన్స్',
    language: 'telugu',
    tags: 'సైన్స్,జీవశాస్త్రం,పత్రహరితం',
  },

  // ────────────────────────────────────────────────────────────
  // PEDAGOGY / PSYCHOLOGY (సైకాలజీ & బోధనా పద్ధతులు)
  // ────────────────────────────────────────────────────────────
  {
    id: 'cdp-dev-01',
    question_id: 'CDP_DEV_001',
    medium: 'english',
    subject: 'Pedagogy',
    class_level: 'SGT',
    chapter: 'Psychology',
    topic: 'Child Development & Learning',
    subtopic: 'Piaget Cognitive Stages',
    difficulty: 'Medium',
    question_type: 'MCQ',
    question: 'According to Jean Piaget, at which stage does a child develop "Object Permanence"?',
    option_a: 'Sensorimotor Stage (0-2 years)',
    option_b: 'Pre-operational Stage (2-7 years)',
    option_c: 'Concrete Operational Stage (7-11 years)',
    option_d: 'Formal Operational Stage (11+ years)',
    correct_answer: 'A',
    explanation: 'Object permanence (understanding that objects continue to exist even when they cannot be seen) is acquired during the Sensorimotor stage (typically by 8-12 months).',
    source_type: 'D.Ed Child Psychology',
    language: 'english',
    tags: 'pedagogy,piaget,psychology',
  },
  {
    id: 'cdp-dev-01-tel',
    question_id: 'CDP_DEV_001_TEL',
    medium: 'telugu',
    subject: 'Pedagogy',
    class_level: 'SGT',
    chapter: 'సైకాలజీ',
    topic: 'వికాస నియమాలు & సిద్ధాంతాలు',
    subtopic: 'పియాజే సంజ్ఞానాత్మక వికాసం',
    difficulty: 'Medium',
    question_type: 'MCQ',
    question: 'జీన్ పియాజే ప్రకారం పిల్లల్లో "వస్తు స్థిరత్వ భావన" (Object Permanence) ఏ దశలో ఏర్పడుతుంది?',
    option_a: 'ఇంద్రియ చాలక దశ (0-2 సం.)',
    option_b: 'పూర్వ ప్రచాలక దశ (2-7 సం.)',
    option_c: 'మూర్త ప్రచాలక దశ (7-11 సం.)',
    option_d: 'అమూర్త ప్రచాలక దశ (11+ సం.)',
    correct_answer: 'A',
    explanation: 'కంటికి కనిపించకపోయినా వస్తువులు ఉనికిలోనే ఉంటాయని గ్రహించే వస్తు స్థిరత్వ భావన ఇంద్రియ చాలక దశ చివరిలో (8-12 నెలల్లో) అభివృద్ధి చెందుతుంది.',
    source_type: 'డి.ఎడ్ బాలల మనోవిజ్ఞాన శాస్త్రం',
    language: 'telugu',
    tags: 'సైకాలజీ,పియాజే,బోధనా పద్ధతులు',
  },
]
